"""Combine PetKit + a pet spec into one self-contained script to paste into Studio's Command Bar.

Usage: python3 assemble.py pets/Koi.lua [--variant Golden,Huge] [-o out.lua]
Without -o the script goes to stdout.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.join(HERE, "..", "templates", "PetKit.lua")


def assemble(pet_path, variant=None):
    kit = open(KIT).read().rstrip()
    pet = open(pet_path).read()
    if variant:
        names = ", ".join('"%s"' % v.strip() for v in variant.split(","))
        pet, n = re.subn(r"^local VARIANT = .*$", "local VARIANT = { %s }" % names, pet, count=1, flags=re.M)
        if n == 0:
            sys.exit("assemble: %s has no 'local VARIANT = ...' line" % pet_path)
    name = os.path.splitext(os.path.basename(pet_path))[0]
    return (
        "-- %s pet: generated by the roblox-pet-builder skill.\n"
        "-- Paste this whole script into Roblox Studio's Command Bar (View > Command Bar) and press Enter.\n"
        "local PetKit = (function()\n%s\nend)()\n\n%s" % (name, kit, pet)
    )


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("pet")
    ap.add_argument("--variant")
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    src = assemble(a.pet, a.variant)
    if a.out:
        open(a.out, "w").write(src)
        print("wrote", a.out)
    else:
        sys.stdout.write(src)
